name: Go Tests

on:
  push:
    branches: [ "master", "main", "*" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Initialize Go module
      run: go mod tidy
    
    - name: Run tests
      run: go test ./...
    
    - name: Run tests with race detector
      run: go test -race ./...
